apiVersion: v1
kind: Pod
metadata:
  name: parsec-pod
  labels:
    numapolicy: numaaware

spec:
  containers:
    # See https://github.com/Spirals-Team/benchmark-containers/tree/master/parsec-3.0 for more information on image.
  - name: parsec-ctn
    image: spirals/parsec-3.0:latest
    command: ["/bin/bash"]
    args: ["-c", "./run -S parsec -a run -p canneal -i simmedium"]
    resources:
      requests:
        cpu: "0.5"
        memory: "4Gi"
      limits:
        cpu: "0.5"
        memory: "4Gi"

  restartPolicy: "Never"
  # Borrowed from https://gist.github.com/balajismaniam/fac7923f6ee44f1f36969c29354e3902
