apiVersion: v1
kind: Pod
metadata:
  name: couchbase-server

spec:
  containers:
  - name: couchbase-ctn
    image: couchbase:latest
    ports:
      - name: admin
        containerPort: 8091
      - name: views
        containerPort: 8092
    resources:
      requests:
        cpu: "0.5"
        memory: "4Gi"
      limits:
        cpu: "0.5"
        memory: "4Gi"
