apiVersion: v1
kind: Pod
metadata:
  name: couchbase-server

spec:
  containers:
  - name: couchbase-ctn
    image: couchbase:latest
    resources:
      requests:
        cpu: "0.5"
        memory: "4Gi"
      limits:
        cpu: "0.5"
        memory: "4Gi"

# sudo kubectl --kubeconfig /etc/kubernetes/admin.conf port-forward pods/couchbase-server 8091:8091
