apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  selector:
    app: couchbase
  ports:
    - name: admin
      protocol: TCP
      port: 8091
      nodePort: 8091
    - name: views
      protocol: TCP
      port: 8092
      nodePort: 8092
  type: NodePort
