apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-deployment
  labels:
    app: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      name: couchbase-server
      labels:
        app: couchbase

    spec:
      containers:
      - name: couchbase-ctn
        image: couchbase:latest
        ports:
          - name: admin
            containerPort: 8091
          - name: views
            containerPort: 8092
          - name: query
            containerPort: 8093
          - name: search
            containerPort: 8094
          - name: data
            containerPort: 11210
          - name: moxi
            containerPort: 11211
        resources:
          requests:
            cpu: "0.5"
            memory: "4Gi"
          limits:
            cpu: "0.5"
            memory: "4Gi"
