apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-deployment
  labels:
    app: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      name: couchbase-server
      labels:
        app: couchbase

    spec:
      containers:
      - name: couchbase-ctn
        image: couchbase:latest
        ports:
          - name: admin
            containerPort: 8091
          - name: views
            containerPort: 8092
        command: ["/bin/bash"]
        args: ["-c", "/opt/couchbase/bin/couchbase-cli cluster-init --cluster-username=carlos --cluster-password=mowgli19 --cluster-ramsize=1024 --cluster-index-ramsize=128"]
        resources:
          requests:
            cpu: "0.5"
            memory: "4Gi"
          limits:
            cpu: "0.5"
            memory: "4Gi"
