apiVersion: v1
kind: Pod
metadata:
  name: parsec-pod
  labels:
    socketpolicy: separate
spec:
  containers:
    # See https://github.com/Spirals-Team/benchmark-containers/tree/master/parsec-3.0 for more information on image.
  - name: parsec-ctn
    image: spirals/parsec-3.0:latest
    command: ["/bin/bash"]
    args: ["-c", "./run -S parsec -a run -p blackscholes -i simsmall"]
    resources:
      requests:
        # Note: CPU request and limit should be same.
        cpu: "1"
        memory: "8Gi"
      limits:
        # Note: CPU request and limit should be same.
        cpu: "1"
        memory: "8Gi"
  restartPolicy: "Never"
  # Borrowed from https://gist.github.com/balajismaniam/fac7923f6ee44f1f36969c29354e3902
